language: node_js
node_js:
- 7

before_install:
- yarn

before_script:
- echo "RENDER_GRAPH_URL: $RENDER_GRAPH_URL" >> .env.yml
- echo "GRAPH_URL: $GRAPH_URL" >> .env.yml

script:
- serverless deploy
