language: node_js
node_js:
- 7

before_script:
- mv env.yml.dist env.yml
- sed -i "s#\$RENDER_GRAPH_URL#$RENDER_GRAPH_URL#g" env.yml
- sed -i "s#\$BUCKET_NAME#$BUCKET_NAME#g" env.yml

script:
- serverless deploy

cache:
  directories:
    - node_modules
